<?php

use yii\db\Migration;

/**
 * Миграция для заполнения таблицы страховых компаний данными из РСА
 */
class m251222_200000_insert_insurance_companies_data extends Migration
{
    /**
     * Преобразование даты из формата "19.июл.17" в "2017-07-19"
     */
    private function parseDate($dateStr)
    {
        if (empty($dateStr) || $dateStr == '') {
            return null;
        }
        
        $months = [
            'янв' => '01', 'фев' => '02', 'мар' => '03', 'апр' => '04',
            'май' => '05', 'июн' => '06', 'июл' => '07', 'авг' => '08',
            'сен' => '09', 'окт' => '10', 'ноя' => '11', 'дек' => '12'
        ];
        
        // Формат: "19.июл.17" или "15.мар.16"
        if (preg_match('/(\d+)\.([а-я]+)\.(\d+)/u', $dateStr, $matches)) {
            $day = str_pad($matches[1], 2, '0', STR_PAD_LEFT);
            $month = $months[mb_strtolower($matches[2], 'UTF-8')] ?? '01';
            $year = '20' . $matches[3];
            return "$year-$month-$day";
        }
        
        return null;
    }

    /**
     * {@inheritdoc}
     */
    public function safeUp()
    {
        $companies = [
            [
                'full_name' => 'Общество с ограниченной ответственностью "Абсолют Страхование"',
                'short_name' => 'ООО "Абсолют Страхование"',
                'previous_name' => 'Общество с ограниченной ответственностью Информационно - страховая компания "ИСК Евро - Полис" (до 03.03.2016)',
                'license_number' => 'ОС № 2496-03',
                'license_date' => $this->parseDate('19.июл.17'),
                'rsa_certificate_number' => '214',
                'rsa_certificate_date' => $this->parseDate('15.мар.16'),
                'phone_fax' => '(495) 025-77-77',
                'email' => 'info@absolutins.ru',
                'website' => 'absolutins.ru',
                'address' => 'ул. Ленинская Слобода, д. 26, г. Москва, 115280',
                'inn' => '7728178835',
            ],
            [
                'full_name' => 'Общество с ограниченной ответственностью "Страховая фирма "Адонис"',
                'short_name' => 'ООО "СФ "Адонис"',
                'previous_name' => '',
                'license_number' => 'ОС № 0585-03',
                'license_date' => $this->parseDate('21.дек.22'),
                'rsa_certificate_number' => '215',
                'rsa_certificate_date' => $this->parseDate('16.сен.13'),
                'phone_fax' => '(342) 241-02-87, 241-02-88, 241-10-68 (факс)',
                'email' => 'info@adonis.perm.ru',
                'website' => 'adonis.perm.ru',
                'address' => 'ш. Космонавтов, д. 111И к.1, помещ.1, ком. 111, г. Пермь, г.о. Пермский, Пермский край, 614066',
                'inn' => '5905013608',
            ],
            [
                'full_name' => 'Акционерное общество "АльфаСтрахование"',
                'short_name' => 'АО "АльфаСтрахование"',
                'previous_name' => 'Открытое акционерное общество "АльфаСтрахование" (до 20.09.2017)',
                'license_number' => 'ОС № 2239-03',
                'license_date' => $this->parseDate('16.сен.24'),
                'rsa_certificate_number' => '11',
                'rsa_certificate_date' => $this->parseDate('14.окт.02'),
                'phone_fax' => '788-09-99; 788-08-88 (факс)',
                'email' => 'alfastrah@alfastrah.ru',
                'website' => 'alfastrah.ru',
                'address' => 'пр-кт Лихачёва, д. 15, помещ. 2/15, вн.тер.г. Муниципальный округ Даниловский, г. Москва, 115280',
                'inn' => '7713056834',
            ],
            [
                'full_name' => 'Акционерное общество Страховая компания "Армеец"',
                'short_name' => 'АО СК "Армеец"',
                'previous_name' => 'ОАО "Страховая компания "Итиль" (до 14.04.2014); ОАО СК "Итиль Армеец" (до 25.09.2015); АО СК "Итиль Армеец" (до 07.06.2016)',
                'license_number' => 'ОС № 1858-03',
                'license_date' => $this->parseDate('11.авг.16'),
                'rsa_certificate_number' => '67',
                'rsa_certificate_date' => $this->parseDate('19.мар.03'),
                'phone_fax' => '(495) 730-06-00',
                'email' => 'armeec@armeec.ru',
                'website' => 'armeec.ru',
                'address' => 'Ленинградский пр-т, д. 20, стр. 1, г. Москва, 125040',
                'inn' => '1656000493',
            ],
            [
                'full_name' => 'Акционерное общество "Страховая компания "Астро-Волга"',
                'short_name' => 'АО "СК "Астро-Волга"',
                'previous_name' => 'Открытое акционерное общество"Страховая компания"Самара-РОСНО"(до 23.04.04), ОАО "СК "Самара" (до 09.10.2012); ОАО "СК "Астро-Волга" (до 11.08.2015)',
                'license_number' => 'ОС № 2619-03',
                'license_date' => $this->parseDate('22.янв.18'),
                'rsa_certificate_number' => '125',
                'rsa_certificate_date' => $this->parseDate('22.окт.15'),
                'phone_fax' => '(846) 200-77-60 ',
                'email' => 'sk@astrovolga.ru',
                'website' => 'astrovolga.ru',
                'address' => 'ул. Арцыбушевская, д. 167, г. Самара, 443001 (фактический адрес: пр. Карла Маркса, д. 201Б, г. Самара, 443080)',
                'inn' => '6315232133',
            ],
            [
                'full_name' => 'Акционерное общество Страховая компания "БАСК"',
                'short_name' => 'АО СК "БАСК"',
                'previous_name' => 'ОАО СК "БАСК" (до 05.07.2018)',
                'license_number' => 'ОС № 0518-03',
                'license_date' => $this->parseDate('25.сен.18'),
                'rsa_certificate_number' => '20',
                'rsa_certificate_date' => $this->parseDate('14.окт.02'),
                'phone_fax' => '(38452) 2-22-17, 2-11-30 (факс), (495) 926-48-10 (тел/факс)',
                'email' => 'central.office@icbask.com; central.office@icbask.ru',
                'website' => 'icbask.ru',
                'address' => 'пер. Цинкзаводской, д. 8А, г. Белово, Кемеровская обл., 652600',
                'inn' => '4202000716',
            ],
            [
                'full_name' => 'Акционерное общество "Боровицкое страховое общество"',
                'short_name' => 'АО "Боровицкое страховое общество"',
                'previous_name' => 'Открытое акционерное общество "Британское страховое общество" (до 16.01.2009г.); Открытое акционерное общество "Боровицкое страховое общество" (до 08.06.2015)',
                'license_number' => 'ОС № 3064-03',
                'license_date' => $this->parseDate('12.мар.24'),
                'rsa_certificate_number' => '151',
                'rsa_certificate_date' => $this->parseDate('25.июн.15'),
                'phone_fax' => '(495) 540-51-10 - многоканальный',
                'email' => 'info@bsoinsur.ru',
                'website' => 'bsoinsur.ru',
                'address' => 'ул. Мытная, д. 1, стр. 1, вн.тер.г. муниципальный округ Якиманка, г. Москва, 119049',
                'inn' => '7714034590',
            ],
            [
                'full_name' => 'Страховое акционерное общество "ВСК"',
                'short_name' => 'САО "ВСК"',
                'previous_name' => 'Открытое акционерное общество "Военно-страховая компания" (до 13.12.2010); СОАО "ВСК" (до 06.12.2014)',
                'license_number' => 'ОС № 0621-03',
                'license_date' => $this->parseDate('11.сен.15'),
                'rsa_certificate_number' => '5',
                'rsa_certificate_date' => $this->parseDate('06.апр.22'),
                'phone_fax' => '785-27-76; 924-34-34 (факс)',
                'email' => 'info@vsk.ru; Sergei.Savin@vsk.ru',
                'website' => 'vsk.ru',
                'address' => 'ул. Островная, д. 4, г. Москва, 121552',
                'inn' => '7710026574',
            ],
            [
                'full_name' => 'Общество с ограниченной ответственностью Страховая Компания "Гелиос"',
                'short_name' => 'ООО Страховая Компания "Гелиос"',
                'previous_name' => 'Общество с ограниченной ответственностью Страховая компания "Гелиос Резерв" (до 28.05.2015)',
                'license_number' => 'ОС № 0397-03',
                'license_date' => $this->parseDate('16.сен.15'),
                'rsa_certificate_number' => '216',
                'rsa_certificate_date' => $this->parseDate('19.дек.12'),
                'phone_fax' => '(495) 981-96-33',
                'email' => 'secretary@skgelios.ru',
                'website' => 'skgelios.ru',
                'address' => 'ул. Новокузнечная, д. 40, офис 68, г. Краснодар, г.о. город Краснодар, Краснодарский край, 350015',
                'inn' => '7705513090',
            ],
            [
                'full_name' => 'Акционерное общество "Страховая компания "Двадцать первый век"',
                'short_name' => 'АО СК "Двадцать первый век"',
                'previous_name' => 'ЗАО СК "Двадцать первый век" (до 23.01.2017)',
                'license_number' => 'ОС № 2027-03',
                'license_date' => $this->parseDate('17.май.22'),
                'rsa_certificate_number' => '185',
                'rsa_certificate_date' => $this->parseDate('03.мар.05'),
                'phone_fax' => '(812) 331-25-20; 541-87-36 ',
                'email' => 'main@21-vek.spb.ru',
                'website' => '21-vek.spb.ru',
                'address' => 'Литейный пр-т, д. 57а, литера А,  вн.тер.г. Муниципальный округ Литейный округ,г. Санкт-Петербург, 190000',
                'inn' => '7817021522',
            ],
            [
                'full_name' => 'Общество с ограниченной ответственностью "РУССКОЕ СТРАХОВОЕ ОБЩЕСТВО "ЕВРОИНС"',
                'short_name' => 'ООО РСО "ЕВРОИНС"',
                'previous_name' => 'ООО СК "БАЗАЛЬТ" (до 22.12.2008г.)',
                'license_number' => 'ОС № 3954-03',
                'license_date' => $this->parseDate('07.июл.15'),
                'rsa_certificate_number' => '211',
                'rsa_certificate_date' => $this->parseDate('17.фев.10'),
                'phone_fax' => '(4812) 68-37-00 (тел/факс); (495) 926-51-55 (тел/факс)',
                'email' => 'pvu@euro-ins.ru',
                'website' => 'euro-ins.ru',
                'address' => 'ул. Глинки, д. 7, этаж 2, пом. 9, г. Смоленск, 214000',
                'inn' => '7714312079',
            ],
            [
                'full_name' => 'Акционерное общество "Зетта Страхование"',
                'short_name' => 'АО "Зетта Страхование"',
                'previous_name' => 'ОАО "РОСНО" (до 13.12.2011), ОАО СК "Альянс" (до 02.06.2023) ',
                'license_number' => 'ОС № 0290-03',
                'license_date' => $this->parseDate('23.май.24'),
                'rsa_certificate_number' => '232',
                'rsa_certificate_date' => $this->parseDate('27.май.24'),
                'phone_fax' => '(495) 956-21-05 доб. 6010',
                'email' => 'info@zettains.ru',
                'website' => 'zettains.ru',
                'address' => '115184, г. Москва, Озерковская наб., д. 30',
                'inn' => '7702073683',
            ],
            [
                'full_name' => 'Страховое публичное акционерное общество "Ингосстрах"',
                'short_name' => 'СПАО "Ингосстрах"',
                'previous_name' => 'ОСАО "Ингосстрах" (до 17.06.2015)',
                'license_number' => 'ОС № 0928-03',
                'license_date' => $this->parseDate('23.сен.15'),
                'rsa_certificate_number' => '1',
                'rsa_certificate_date' => $this->parseDate('14.мар.16'),
                'phone_fax' => ' 956-55-55 (справки по ДТП); 234-36-48 (орг), 959-41-53 (юр),   959- 44-05 (факс)',
                'email' => 'ingos24@ingos.ru; Ilya.Solomatin@ingos.ru; Anatoly.Samsonov@ingos.ru; Irina.Pavlova@ingos.ru',
                'website' => 'ingos.ru',
                'address' => 'ул. Пятницкая, д. 12, стр. 2, г. Москва, 115035',
                'inn' => '7705042179',
            ],
            [
                'full_name' => 'Общество с ограниченной ответственностью "Страховая компания "ИНСАЙТ"',
                'short_name' => 'ООО "СК "ИНСАЙТ"',
                'previous_name' => 'Общество с ограниченной ответственностью страховая компания "ПРОФСОДРУЖЕСТВО" (до 14.10.2019)',
                'license_number' => 'ОС № 2682-03',
                'license_date' => $this->parseDate('02.фев.23'),
                'rsa_certificate_number' => '230',
                'rsa_certificate_date' => $this->parseDate('27.фев.23'),
                'phone_fax' => '(495) 025-03-10',
                'email' => 'insight@insightins.ru',
                'website' => 'insightins.ru',
                'address' => 'дорога Балтия, д. 25 км, Литера 11Б, эт/пом/ком 3/1/84, деревня Михалково, город Красногорск, Московская область, 143420',
                'inn' => '7704449282',
            ],
            [
                'full_name' => 'Акционерное общество "Московская акционерная страховая компания"',
                'short_name' => 'АО "МАКС"',
                'previous_name' => 'Закрытое акционерное общество "Московская акционерная страховая компания" (до 15.05.2018)',
                'license_number' => 'ОС № 1427-03',
                'license_date' => $this->parseDate('18.июн.18'),
                'rsa_certificate_number' => '12',
                'rsa_certificate_date' => $this->parseDate('25.май.18'),
                'phone_fax' => '(495) 730-11-01; 540-11-01; 951-19-01 (факс)',
                'email' => 'info@makc.ru; autoins@makc.ru',
                'website' => 'makc.ru',
                'address' => 'ул. Малая Ордынка, д. 50, г. Москва, 115184',
                'inn' => '7709031643',
            ],
            [
                'full_name' => 'Страховое Акционерное Общество "Медэкспресс"',
                'short_name' => 'САО "Медэкспресс"',
                'previous_name' => 'СЗАО "Медэкспресс" (до 13.07.2015)',
                'license_number' => 'ОС № 0141-03',
                'license_date' => $this->parseDate('21.сен.15'),
                'rsa_certificate_number' => '29',
                'rsa_certificate_date' => $this->parseDate('14.окт.02'),
                'phone_fax' => '(812) 494-94-11; 494-94-10 (факс)',
                'email' => 'admin@medexpress.ru',
                'website' => 'medexpress.ru',
                'address' => 'ул. Гороховая, д. 14/26, г. Санкт-Петербург, 191186',
                'inn' => '7803025365',
            ],
            [
                'full_name' => 'Акционерное общество "Объединенная страховая компания"',
                'short_name' => 'АО "ОСК"',
                'previous_name' => 'Закрытое акционерное общество "Страховая компания "Самара-АСКО" (до 09.07.2009); Закрытое акционерное общество "Объединенная страховая компания" (до 29.01.2015)',
                'license_number' => 'ОС № 2346-03',
                'license_date' => $this->parseDate('18.мар.25'),
                'rsa_certificate_number' => '84',
                'rsa_certificate_date' => $this->parseDate('08.июн.15'),
                'phone_fax' => '(846) 212-99-55',
                'email' => 'info@osk-ins.ru',
                'website' => 'osk-ins.ru',
                'address' => 'ул. Ленинская, д. 168, офис 2, г. Самара, вн.р-н Ленинский, г.о. Самара, Самарская область, 443041',
                'inn' => '6312013969',
            ],
            [
                'full_name' => 'Акционерное общество "Страховая компания "ПАРИ"',
                'short_name' => 'АО "СК "ПАРИ"',
                'previous_name' => 'ОАО "СК "ПАРИ" (до 29.04.2015)',
                'license_number' => 'ОС № 0915-03',
                'license_date' => $this->parseDate('03.июл.15'),
                'rsa_certificate_number' => '31',
                'rsa_certificate_date' => $this->parseDate('14.окт.02'),
                'phone_fax' => '(495) 721-12-21; 788-57-20 (факс)',
                'email' => 'ic@skpari.ru',
                'website' => 'skpari.ru',
                'address' => 'ул. Расковой, д. 34, стр. 14, г. Москва, 127015',
                'inn' => '7704041020',
            ],
            [
                'full_name' => 'Общество с ограниченной ответственностью Страховая компания "Паритет-СК"',
                'short_name' => 'ООО СК "Паритет-СК"',
                'previous_name' => '',
                'license_number' => 'ОС № 3268-03',
                'license_date' => $this->parseDate('07.июн.22'),
                'rsa_certificate_number' => '231',
                'rsa_certificate_date' => $this->parseDate('15.дек.22'),
                'phone_fax' => '(495) 617-10-90',
                'email' => 'info@paritet-sk.com',
                'website' => 'paritet-sk.ru',
                'address' => 'Севастопольский пр-кт, д. 11Г, этаж 5, помещ. 8, вн.тер.г. муниципальный округ Котловка, г. Москва, 117447',
                'inn' => '7705233021',
            ],
            [
                'full_name' => 'Публичное акционерное общество "Группа Ренессанс Страхование"',
                'short_name' => 'ПАО "Группа Ренессанс Страхование"',
                'previous_name' => 'ООО "Группа Ренессанс Страхование" (до 05.09.2018); АО "Группа Ренессанс Страхование" (до 06.10.2021)',
                'license_number' => 'ОС № 1284-03',
                'license_date' => $this->parseDate('12.фев.24'),
                'rsa_certificate_number' => '72',
                'rsa_certificate_date' => $this->parseDate('13.сен.18'),
                'phone_fax' => '725-10-50; 967-35-35 (факс)',
                'email' => 'info@renins.com; regul@renins.com',
                'website' => 'renins.ru',
                'address' => 'ул. Крылатская, д. 17, к. 1, вн.тер. Муниципальный округ Крылатское, г. Москва, 121614',
                'inn' => '7725497022',
            ],
            [
                'full_name' => 'Страховое акционерное общество "РЕСО-Гарантия"',
                'short_name' => 'САО "РЕСО-Гарантия"',
                'previous_name' => 'ОСАО "РЕСО-Гарантия" (до 03.06.2015); СПАО "РЕСО-Гарантия" (до 20.07.2020)',
                'license_number' => 'ОС № 1209-03',
                'license_date' => $this->parseDate('22.фев.22'),
                'rsa_certificate_number' => '6',
                'rsa_certificate_date' => $this->parseDate('12.июл.04'),
                'phone_fax' => '730-30-00; доб.1682 (факс)',
                'email' => 'mail@reso.ru',
                'website' => 'reso.ru',
                'address' => 'проезд Нагорный, д. 6, стр. 9, этаж 3, комната 1, вн.тер.г. муниципальный округ Нагорный, г. Москва, 117105',
                'inn' => '7710045520',
            ],
            [
                'full_name' => 'Публичное акционерное общество Страховая Компания "Росгосстрах"',
                'short_name' => 'ПАО СК "Росгосстрах"',
                'previous_name' => 'ОАО "Росгосстрах" (до 23.11.2015); ПАО "Росгосстрах" (14.04.2016)',
                'license_number' => 'ОС № 0001-03',
                'license_date' => $this->parseDate('06.июн.18'),
                'rsa_certificate_number' => '3',
                'rsa_certificate_date' => $this->parseDate('12.май.16'),
                'phone_fax' => '783-24-24 (доб.2683) 783-24-70; 783-24-34 (тел/факс)',
                'email' => 'rgs@rgs.ru; Elena_Kostyrko@rgs.ru; Olga_Veresova@rgs.ru',
                'website' => 'rgs.ru',
                'address' => 'ул. Киевская, д. 7, к. 1, вн.тер.г. муниципальный округ Дорогомилово, г. Москва, 121059',
                'inn' => '7707067683',
            ],
            [
                'full_name' => 'Общество с ограниченной ответственностью Страховая компания "Сбербанк страхование"',
                'short_name' => 'ООО СК "Сбербанк страхование"',
                'previous_name' => '',
                'license_number' => 'ОС № 4331-03',
                'license_date' => $this->parseDate('10.июн.21'),
                'rsa_certificate_number' => '229',
                'rsa_certificate_date' => $this->parseDate('02.июл.21'),
                'phone_fax' => '(495) 139-21-29',
                'email' => 'info@sberins.ru',
                'website' => 'sberbankins.ru',
                'address' => 'ул. Поклонная, д. 3, корп. 1, этаж 1, помещение 3, г. Москва, 121170',
                'inn' => '7706810747',
            ],
            [
                'full_name' => 'Акционерное общество "Совкомбанк страхование"',
                'short_name' => '"Совкомбанк страхование" (АО)',
                'previous_name' => 'Открытое акционерное общество Страховая компания "Класс" (до 12.03.2008); КИТ Финанс Страхование (ОАО) (до 21.02.2013); Либерти Страхование (ОАО) (до 23.03.2016); Либерти Страхование (АО) (до 02.04.2020)',
                'license_number' => 'ОС № 1675-03',
                'license_date' => $this->parseDate('26.апр.23'),
                'rsa_certificate_number' => '117',
                'rsa_certificate_date' => $this->parseDate('21.мар.13'),
                'phone_fax' => '(812) 449-47-58',
                'email' => 'Elena.Zhenihova@sovcomins.ru; Anna.Bolshakova@sovcomins.ru; info@sovcomins.ru; state@sovcomins.ru; Aleksandra.Tepponen@sovcomins.ru; Veronika.Koposova@sovcomins.ru',
                'website' => 'sovcomins.ru',
                'address' => 'пр-кт Ленинградский, д. 35, стр. 1, вн.тер.г. муниципальный округ Беговой, г. Москва, 125284',
                'inn' => '7812016906',
            ],
            [
                'full_name' => 'Акционерное общество "Страховое общество газовой промышленности"',
                'short_name' => 'АО "СОГАЗ"',
                'previous_name' => 'ОАО "СОГАЗ" (до 28.05.2015)',
                'license_number' => 'ОС № 1208-03',
                'license_date' => $this->parseDate('05.авг.15'),
                'rsa_certificate_number' => '110',
                'rsa_certificate_date' => $this->parseDate('03.дек.15'),
                'phone_fax' => '(495) 739-21-40 (многоканальный); 739-21-39 (факс)',
                'email' => 'sogaz@sogaz.biz',
                'website' => 'sogaz.ru',
                'address' => 'пр-т Академика Сахарова, д. 10, г. Москва, 107078',
                'inn' => '7736035485',
            ],
            [
                'full_name' => ' Общество с ограниченной ответственностью "Страховая Компания "Согласие"',
                'short_name' => 'ООО "СК "Согласие"',
                'previous_name' => '',
                'license_number' => 'ОС №1307-03',
                'license_date' => $this->parseDate('25.май.15'),
                'rsa_certificate_number' => '2',
                'rsa_certificate_date' => $this->parseDate('14.окт.02'),
                'phone_fax' => '739-01-01; 959-46-02; 959-46-03 (факс); 953-75-63 (ОСАГО)',
                'email' => 'official@soglasie.ru',
                'website' => 'soglasie.ru',
                'address' => 'ул. Гиляровского, д. 42, г. Москва, 129110',
                'inn' => '7706196090',
            ],
            [
                'full_name' => 'Акционерное общество Страховая группа "Спасские ворота"',
                'short_name' => 'АО СГ "Спасские ворота"',
                'previous_name' => 'Открытое акционерное общество "Межрегионгарант"(до 20.10.03); ОАО Страховая группа "Межрегионгарант" (до 29.12.2012); Открытое акционерное общество Страховая группа "Спасские ворота" (до 07.10.2016)',
                'license_number' => 'ОС № 3300-03',
                'license_date' => $this->parseDate('11.янв.21'),
                'rsa_certificate_number' => '56',
                'rsa_certificate_date' => $this->parseDate('14.ноя.16'),
                'phone_fax' => '(499) 402-89-02, 402-89-03, 402-89-07 (факс)',
                'email' => 'info@spasskievorota.com',
                'website' => 'spasskievorota.ru',
                'address' => 'ул. Ибрагимова, д. 15, корп. 2, пом. 201, г. Москва, 105318',
                'inn' => '8901010104',
            ],
            [
                'full_name' => 'Акционерное общество "Страховая бизнес группа"',
                'short_name' => 'АО  "Страховая бизнес группа"',
                'previous_name' => 'Закрытое акционерное общество "Страховая компания "Рекон"( до 08.07.2005): ЗАО  "Страховая бизнес группа" (до 26.08.2015)',
                'license_number' => 'ОС № 3229 03',
                'license_date' => $this->parseDate('02.окт.15'),
                'rsa_certificate_number' => '172',
                'rsa_certificate_date' => $this->parseDate('24.авг.05'),
                'phone_fax' => '(473) 250-20-50',
                'email' => 'office@ibg.ru',
                'website' => 'ibg.ru',
                'address' => 'Ул. Платонова, 16, г. Воронеж, 394018',
                'inn' => '3666068423',
            ],
            [
                'full_name' => 'Акционерное общество "Страховое общество "Талисман"',
                'short_name' => 'АО "СО "Талисман"',
                'previous_name' => 'ОАО "Страховое общество "Талисман" (до 12.08.2015)',
                'license_number' => 'ОС № 1587-03',
                'license_date' => $this->parseDate('22.сен.15'),
                'rsa_certificate_number' => '177',
                'rsa_certificate_date' => $this->parseDate('21.окт.04'),
                'phone_fax' => '(843) 264-57-80',
                'email' => 'info@talisman-so.ru',
                'website' => 'talisman-so.ru',
                'address' => 'ул. Пушкина, д. 11, помещ. 3, г. Казань, г.о. город Казань, Республика Татарстан, 420111',
                'inn' => '1655004449',
            ],
            [
                'full_name' => 'Акционерное общество "Т-Страхование"',
                'short_name' => 'АО "Т-Страхование"',
                'previous_name' => 'ОАО "СК "Москва" (до 22.11.2013); Открытое акционерное общество "Тинькофф Онлайн Страхование" (до 05.01.2015); Акционерное общество "Тинькофф Страхование" (до 20.06.2024)',
                'license_number' => 'ОС № 0191-03',
                'license_date' => $this->parseDate('01.июл.24'),
                'rsa_certificate_number' => '210',
                'rsa_certificate_date' => $this->parseDate('05.авг.24'),
                'phone_fax' => '8-800-700-55-00',
                'email' => 'rsa@tinsurance.ru',
                'website' => 'tinsurance.ru',
                'address' => '2-я Хуторская ул., д. 38А, стр. 26, г. Москва, 127287',
                'inn' => '7704082517',
            ],
            [
                'full_name' => 'Акционерное общество Страховая компания "Чулпан"',
                'short_name' => 'АО СК "Чулпан"',
                'previous_name' => 'ЗАО СК "Чулпан" (до 21.10.2014)',
                'license_number' => 'ОС № 1216-03',
                'license_date' => $this->parseDate('24.июн.21'),
                'rsa_certificate_number' => '144',
                'rsa_certificate_date' => $this->parseDate('09.сен.03'),
                'phone_fax' => '(8553) 45-42-42; 45-53-32; 45-35-96; 45-36-01 (факс)',
                'email' => 'guzelf@chulpan.ru; chulpan@tatais.ru',
                'website' => 'chulpan.ru',
                'address' => 'ул. Пушкина, д. 66, пом. 1, г. Альметьевск, Республика Татарстан, 423452',
                'inn' => '1644001196',
            ],
            [
                'full_name' => 'Публичное акционерное общество "Страховая акционерная компания "ЭНЕРГОГАРАНТ"',
                'short_name' => 'ПАО "САК "ЭНЕРГОГАРАНТ"',
                'previous_name' => 'ОАО "САК "ЭНЕРГОГАРАНТ" (до 30.10.2015)',
                'license_number' => 'ОС № 1834-03',
                'license_date' => $this->parseDate('01.фев.16'),
                'rsa_certificate_number' => '46',
                'rsa_certificate_date' => $this->parseDate('14.окт.02'),
                'phone_fax' => '(495) 737-03-30 (тел/факс), 737-03-17 (тел/факс)',
                'email' => 'motor@msk-garant.ru',
                'website' => 'energogarant.ru',
                'address' => 'Садовническая набережная, д. 23, г. Москва, 115035',
                'inn' => '7705041231',
            ],
            [
                'full_name' => 'Акционерное общество "Группа страховых компаний "Югория"',
                'short_name' => 'АО "ГСК "Югория"',
                'previous_name' => 'ГпХМАО "ГСК "Югория"(до10.09.2004); Открытое акционерное общество "Государственная страховая компания "Югория" (до 08.02.2016); Акционерное общество "Государственная страховая компания "Югория" (до 07.08.2019)',
                'license_number' => 'ОС № 3211-03',
                'license_date' => $this->parseDate('26.авг.19'),
                'rsa_certificate_number' => '48',
                'rsa_certificate_date' => $this->parseDate('06.апр.05'),
                'phone_fax' => '(3467) 357-222; 357-224 (факс) Московское представительство: (495) 970-10-70',
                'email' => 'rsa@ugsk.ru',
                'website' => 'ugsk.ru',
                'address' => 'ул. Комсомольская, д. 61, г. Ханты-Мансийск, 628011 ',
                'inn' => '8601023568',
            ],
        ];

        foreach ($companies as $company) {
            $this->insert('{{%insurance_company}}', $company);
        }
    }

    /**
     * {@inheritdoc}
     */
    public function safeDown()
    {
        $this->truncateTable('{{%insurance_company}}');
    }
}

